name = input("Enter your name? ")
surname = input("Enter your surname? ")
age = input("How old are you? ")
email = input("Enter your email: ")
Birth_year = input("Enter your birth year: ")
Birthday = input("Enter your birthday: ")

print(name)
print(surname)
print(age)
print(email)
print(Birth_year)
print(Birthday) 
print("Welcome" + name)